### ISSUE TITLE
Don't display pulse during workout or in graph when not recorded / 0

### ISSUE THREAD

**Issue by andreasvc** [svenmeier/coxswain#50] opened 2017-02-10 16:08 UTC
When not displayed during workout, could be replaced by energy (kcal).

**Comment by svenmeier** [comment] 2017-02-10 17:05
Closing as duplicate of #53

**Comment by andreasvc** [comment] 2017-02-10 17:08
It's not a duplicate of #53, I'm suggesting the absence of the heart rate monitor should trigger not displaying pulse information.

**Comment by svenmeier** [comment] 2020-06-29 11:19
The user can choose what values to display via long-press. I won't add an automatic replacement.

**Closed by svenmeier** 2020-06-29 11:19 UTC
